### ISSUE TITLE
Remove tmp models files under /tmp/models/ after torchserve --stop

### ISSUE THREAD

**Issue by spate141** [pytorch/serve#718]
- Version: `torchserve == 0.2.0`
- Issue: When you start the torchserve; it generate tmp files under `/tmp/models/` which stays there even after you invoke `torchserve --stop`. These files keep piling up and over the time you will run out of disk space. Isn't there any mechanism that deletes these model files once you stop the server?

**Comment by harshbafna** [comment]
@spate141: Currently, the temp model directory is cleaned when a model is unregistered. However, when TorchServe is stopped the models are not unregistered and the server state is dumped into the snapshot.

This is a good catch.

**Comment by maaquib** [comment]
@harshbafna Not sure if this is a bug. If we delete the model temp directory on server stop, won't reload from snapshot fail on server restart?

**Comment by spate141** [comment]
Just some thoughts: How about `torchserve --stop --clear_cache` ? Or, an option with `torchserve --start` that won't make a brand new tmp copy of same model?

**Comment by harshbafna** [comment]
> @harshbafna Not sure if this is a bug. If we delete the model temp directory on server stop, won't reload from snapshot fail on server restart?

@maaquib: TorchServe state restoration from snapshot does not depend on the model's temp directory. It expects the mar file for every model from the snapshot to be present in the model-store.


> Just some thoughts: How about `torchserve --stop --clear_cache` ? Or, an option with `torchserve --start` that won't make a brand new tmp copy of same model?

@spate141: This has been fixed as a part of Windows native support in PR #662, refer to the following code snippet from the PR for more details :

https://github.com/pytorch/serve/pull/662/files#diff-45f9e03a9d3046ef0e2c18e18b0bb9c1889f9e3ff9918568870539cc926e3895R391

**Comment by harshbafna** [comment]
Closing as this has been merged to master.

**Comment by hungtooc** [comment]
i think i'm facing this problem:
![image](https://user-images.githubusercontent.com/24487114/226079104-96ceec95-c3f8-4efd-adb8-5ee60d3b08b2.png)

**Comment by BodaSadalla98** [comment]
This problem still exists, and it caused a huge bug for me, as torchserve kept loading old models in the tmp directory
